"""Add distributed tracing models

Revision ID: 0c7c261b4634
Revises: 2064ef0ac773
Create Date: 2026-03-19 23:20:43.289742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7c261b4634'
down_revision: Union[str, Sequence[str], None] = '2064ef0ac773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('span_id', sa.String(length=16), nullable=False),
    sa.Column('parent_span_id', sa.String(length=16), nullable=True),
    sa.Column('operation', sa.String(length=500), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('span_id')
    )
    op.create_index('idx_spans_service_created', 'spans', ['service_name', 'created_at'], unique=False)
    op.create_index('idx_spans_trace_start', 'spans', ['trace_id', 'start_time'], unique=False)
    op.create_index('idx_spans_user_created', 'spans', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_spans_service_name'), 'spans', ['service_name'], unique=False)
    op.create_index(op.f('ix_spans_tenant_id'), 'spans', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    op.create_index(op.f('ix_spans_user_id'), 'spans', ['user_id'], unique=False)
    op.add_column('incident_events', sa.Column('trace_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_incident_events_trace_id'), 'incident_events', ['trace_id'], unique=False)
    op.add_column('incidents', sa.Column('trace_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_incidents_trace_id'), 'incidents', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_trace_id'), table_name='incidents')
    op.drop_column('incidents', 'trace_id')
    op.drop_index(op.f('ix_incident_events_trace_id'), table_name='incident_events')
    op.drop_column('incident_events', 'trace_id')
    op.drop_index(op.f('ix_spans_user_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_tenant_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_service_name'), table_name='spans')
    op.drop_index('idx_spans_user_created', table_name='spans')
    op.drop_index('idx_spans_trace_start', table_name='spans')
    op.drop_index('idx_spans_service_created', table_name='spans')
    op.drop_table('spans')
    # ### end Alembic commands ###
