"""Add adaptive timeout threshold

Revision ID: 2064ef0ac773
Revises: 5e0e9edd23eb
Create Date: 2026-03-06 23:21:49.451511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2064ef0ac773'
down_revision: Union[str, Sequence[str], None] = '5e0e9edd23eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_thresholds', sa.Column('adaptive_timeout_latency_ms', sa.Integer(), server_default=sa.text('2000'), nullable=False))
    op.add_column('config_overrides', sa.Column('adaptive_timeout_latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config_overrides', 'adaptive_timeout_latency_ms')
    op.drop_column('ai_thresholds', 'adaptive_timeout_latency_ms')
    # ### end Alembic commands ###
