"""add_agentic_payments_tables

Revision ID: 346e37244c61
Revises: ba385c6260d4
Create Date: 2026-06-18 20:25:52.408703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346e37244c61'
down_revision: Union[str, Sequence[str], None] = 'ba385c6260d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('agent_erc8004_score', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('amount_paid_wei', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('access_granted_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_payment_active', 'agent_payments', ['user_id', 'agent_id', 'service_name', 'endpoint', 'status', 'access_granted_until'], unique=False)
    op.create_index(op.f('ix_agent_payments_agent_id'), 'agent_payments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_payments_status'), 'agent_payments', ['status'], unique=False)
    op.create_index(op.f('ix_agent_payments_tx_hash'), 'agent_payments', ['tx_hash'], unique=True)
    op.create_index(op.f('ix_agent_payments_user_id'), 'agent_payments', ['user_id'], unique=False)
    op.create_table('user_agent_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avalanche_wallet', sa.String(length=42), nullable=True),
    sa.Column('payment_amount_wei', sa.String(length=30), server_default=sa.text("'10000000000000000'"), nullable=False),
    sa.Column('access_duration_minutes', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('agentic_payments_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_agent_settings_user_id'), 'user_agent_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_agent_settings_user_id'), table_name='user_agent_settings')
    op.drop_table('user_agent_settings')
    op.drop_index(op.f('ix_agent_payments_user_id'), table_name='agent_payments')
    op.drop_index(op.f('ix_agent_payments_tx_hash'), table_name='agent_payments')
    op.drop_index(op.f('ix_agent_payments_status'), table_name='agent_payments')
    op.drop_index(op.f('ix_agent_payments_agent_id'), table_name='agent_payments')
    op.drop_index('idx_agent_payment_active', table_name='agent_payments')
    op.drop_table('agent_payments')
    # ### end Alembic commands ###
