"""Add hourly and daily signal aggregation tables

Revision ID: 429c109fb142
Revises: 
Create Date: 2026-02-01 17:44:37.563187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429c109fb142'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_aggregates_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('day_bucket', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('min_latency_ms', sa.Float(), nullable=False),
    sa.Column('max_latency_ms', sa.Float(), nullable=False),
    sa.Column('p50_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_service_time', 'signal_aggregates_daily', ['service_name', 'endpoint', 'day_bucket'], unique=False)
    op.create_index('idx_daily_unique', 'signal_aggregates_daily', ['user_id', 'service_name', 'endpoint', 'tenant_id', 'day_bucket'], unique=True)
    op.create_index('idx_daily_user_time', 'signal_aggregates_daily', ['user_id', 'day_bucket'], unique=False)
    op.create_index(op.f('ix_signal_aggregates_daily_day_bucket'), 'signal_aggregates_daily', ['day_bucket'], unique=False)
    op.create_index(op.f('ix_signal_aggregates_daily_service_name'), 'signal_aggregates_daily', ['service_name'], unique=False)
    op.create_index(op.f('ix_signal_aggregates_daily_user_id'), 'signal_aggregates_daily', ['user_id'], unique=False)
    op.create_table('signal_aggregates_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('hour_bucket', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('min_latency_ms', sa.Float(), nullable=False),
    sa.Column('max_latency_ms', sa.Float(), nullable=False),
    sa.Column('p50_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hourly_service_time', 'signal_aggregates_hourly', ['service_name', 'endpoint', 'hour_bucket'], unique=False)
    op.create_index('idx_hourly_unique', 'signal_aggregates_hourly', ['user_id', 'service_name', 'endpoint', 'tenant_id', 'hour_bucket'], unique=True)
    op.create_index('idx_hourly_user_time', 'signal_aggregates_hourly', ['user_id', 'hour_bucket'], unique=False)
    op.create_index(op.f('ix_signal_aggregates_hourly_hour_bucket'), 'signal_aggregates_hourly', ['hour_bucket'], unique=False)
    op.create_index(op.f('ix_signal_aggregates_hourly_service_name'), 'signal_aggregates_hourly', ['service_name'], unique=False)
    op.create_index(op.f('ix_signal_aggregates_hourly_user_id'), 'signal_aggregates_hourly', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_aggregates_hourly_user_id'), table_name='signal_aggregates_hourly')
    op.drop_index(op.f('ix_signal_aggregates_hourly_service_name'), table_name='signal_aggregates_hourly')
    op.drop_index(op.f('ix_signal_aggregates_hourly_hour_bucket'), table_name='signal_aggregates_hourly')
    op.drop_index('idx_hourly_user_time', table_name='signal_aggregates_hourly')
    op.drop_index('idx_hourly_unique', table_name='signal_aggregates_hourly')
    op.drop_index('idx_hourly_service_time', table_name='signal_aggregates_hourly')
    op.drop_table('signal_aggregates_hourly')
    op.drop_index(op.f('ix_signal_aggregates_daily_user_id'), table_name='signal_aggregates_daily')
    op.drop_index(op.f('ix_signal_aggregates_daily_service_name'), table_name='signal_aggregates_daily')
    op.drop_index(op.f('ix_signal_aggregates_daily_day_bucket'), table_name='signal_aggregates_daily')
    op.drop_index('idx_daily_user_time', table_name='signal_aggregates_daily')
    op.drop_index('idx_daily_unique', table_name='signal_aggregates_daily')
    op.drop_index('idx_daily_service_time', table_name='signal_aggregates_daily')
    op.drop_table('signal_aggregates_daily')
    # ### end Alembic commands ###
