"""Add is_agent to Signal

Revision ID: 557d83bac0e3
Revises: de5cc1bb3328
Create Date: 2026-07-01 22:41:52.681067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557d83bac0e3'
down_revision: Union[str, Sequence[str], None] = 'de5cc1bb3328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('is_agent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_signals_is_agent'), 'signals', ['is_agent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_is_agent'), table_name='signals')
    op.drop_column('signals', 'is_agent')
    # ### end Alembic commands ###
