"""add plan_expires_at to users

Revision ID: 5e0e9edd23eb
Revises: f1ff6bdd845c
Create Date: 2026-03-02 13:58:43.499746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0e9edd23eb'
down_revision: Union[str, Sequence[str], None] = 'f1ff6bdd845c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan_expires_at')
    # ### end Alembic commands ###
