"""add_action_taken_to_signals

Revision ID: 6bb7f39ee70e
Revises: f7g8h9i0j1k2
Create Date: 2026-02-28 13:57:32.297163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bb7f39ee70e'
down_revision: Union[str, Sequence[str], None] = 'f7g8h9i0j1k2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ratelimit_lookup'), table_name='rate_limit_configs')
    op.drop_index(op.f('idx_ratelimit_unique'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_endpoint'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_service_name'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_user_id'), table_name='rate_limit_configs')
    op.drop_table('rate_limit_configs')
    op.add_column('signals', sa.Column('action_taken', sa.String(), server_default=sa.text("'none'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'action_taken')
    op.create_table('rate_limit_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('requests_per_minute', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('enabled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('rate_limit_configs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rate_limit_configs_pkey'))
    )
    op.create_index(op.f('ix_rate_limit_configs_user_id'), 'rate_limit_configs', ['user_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_configs_service_name'), 'rate_limit_configs', ['service_name'], unique=False)
    op.create_index(op.f('ix_rate_limit_configs_endpoint'), 'rate_limit_configs', ['endpoint'], unique=False)
    op.create_index(op.f('idx_ratelimit_unique'), 'rate_limit_configs', ['user_id', 'service_name', 'endpoint'], unique=True)
    op.create_index(op.f('idx_ratelimit_lookup'), 'rate_limit_configs', ['user_id', 'service_name', 'endpoint', 'enabled'], unique=False)
    # ### end Alembic commands ###
