"""add_eerc_fields

Revision ID: 93b6b0b415bd
Revises: 557d83bac0e3
Create Date: 2026-07-04 20:49:17.364743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b6b0b415bd'
down_revision: Union[str, Sequence[str], None] = '557d83bac0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_agent_settings', sa.Column('confidential_eerc_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_agent_settings', sa.Column('eerc_token_address', sa.String(length=42), nullable=True))
    op.add_column('user_agent_settings', sa.Column('eerc_payment_amount', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_agent_settings', 'eerc_payment_amount')
    op.drop_column('user_agent_settings', 'eerc_token_address')
    op.drop_column('user_agent_settings', 'confidential_eerc_enabled')
    # ### end Alembic commands ###
