"""add_feature_flags

Revision ID: ba385c6260d4
Revises: 0c7c261b4634
Create Date: 2026-03-20 20:37:03.532641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba385c6260d4'
down_revision: Union[str, Sequence[str], None] = '0c7c261b4634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('rollout_percent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_flag_unique_name', 'feature_flags', ['name', 'service_name'], unique=True)
    op.create_index(op.f('ix_feature_flags_service_name'), 'feature_flags', ['service_name'], unique=False)
    op.create_index(op.f('ix_feature_flags_tenant_id'), 'feature_flags', ['tenant_id'], unique=False)
    op.create_table('flag_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_name', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('old_rollout', sa.Integer(), nullable=False),
    sa.Column('new_rollout', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flag_audit_logs_flag_name'), 'flag_audit_logs', ['flag_name'], unique=False)
    op.create_index(op.f('ix_flag_audit_logs_service_name'), 'flag_audit_logs', ['service_name'], unique=False)
    op.add_column('incidents', sa.Column('flag_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_incidents_flag_name'), 'incidents', ['flag_name'], unique=False)
    op.add_column('signals', sa.Column('flag_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_signals_flag_name'), 'signals', ['flag_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_flag_name'), table_name='signals')
    op.drop_column('signals', 'flag_name')
    op.drop_index(op.f('ix_incidents_flag_name'), table_name='incidents')
    op.drop_column('incidents', 'flag_name')
    op.drop_index(op.f('ix_flag_audit_logs_service_name'), table_name='flag_audit_logs')
    op.drop_index(op.f('ix_flag_audit_logs_flag_name'), table_name='flag_audit_logs')
    op.drop_table('flag_audit_logs')
    op.drop_index(op.f('ix_feature_flags_tenant_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_service_name'), table_name='feature_flags')
    op.drop_index('idx_feature_flag_unique_name', table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
