"""rename stripe_customer_id to razorpay_customer_id

Revision ID: c7261d00b88f
Revises: ff4b0f4cac99
Create Date: 2026-03-02 13:05:57.765893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7261d00b88f'
down_revision: Union[str, Sequence[str], None] = 'ff4b0f4cac99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('razorpay_customer_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.create_index(op.f('ix_users_razorpay_customer_id'), 'users', ['razorpay_customer_id'], unique=True)
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_razorpay_customer_id'), table_name='users')
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.drop_column('users', 'razorpay_customer_id')
    # ### end Alembic commands ###
