"""Add rate_limit_configs table

Revision ID: db51077434eb
Revises: 5a3c8f2d9e1b
Create Date: 2026-02-06 12:55:10.078154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db51077434eb'
down_revision: Union[str, Sequence[str], None] = '5a3c8f2d9e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('enabled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ratelimit_lookup', 'rate_limit_configs', ['user_id', 'service_name', 'endpoint', 'enabled'], unique=False)
    op.create_index('idx_ratelimit_unique', 'rate_limit_configs', ['user_id', 'service_name', 'endpoint'], unique=True)
    op.create_index(op.f('ix_rate_limit_configs_endpoint'), 'rate_limit_configs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_rate_limit_configs_service_name'), 'rate_limit_configs', ['service_name'], unique=False)
    op.create_index(op.f('ix_rate_limit_configs_user_id'), 'rate_limit_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_configs_user_id'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_service_name'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_endpoint'), table_name='rate_limit_configs')
    op.drop_index('idx_ratelimit_unique', table_name='rate_limit_configs')
    op.drop_index('idx_ratelimit_lookup', table_name='rate_limit_configs')
    op.drop_table('rate_limit_configs')
    # ### end Alembic commands ###
