"""Add pay per request fields

Revision ID: de5cc1bb3328
Revises: 346e37244c61
Create Date: 2026-06-29 21:27:13.731178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5cc1bb3328'
down_revision: Union[str, Sequence[str], None] = '346e37244c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_payments', sa.Column('payment_mode', sa.String(length=50), server_default=sa.text("'rate_limit'"), nullable=False))
    op.add_column('user_agent_settings', sa.Column('pay_per_request_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_agent_settings', sa.Column('pay_per_request_amount_wei', sa.String(length=30), nullable=True))
    op.add_column('user_agent_settings', sa.Column('pay_per_request_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_agent_settings', 'pay_per_request_duration_minutes')
    op.drop_column('user_agent_settings', 'pay_per_request_amount_wei')
    op.drop_column('user_agent_settings', 'pay_per_request_enabled')
    op.drop_column('agent_payments', 'payment_mode')
    # ### end Alembic commands ###
