"""Add priority and customer_identifier to signals

Revision ID: e33a78f63e55
Revises: db51077434eb
Create Date: 2026-02-07 20:38:28.803140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33a78f63e55'
down_revision: Union[str, Sequence[str], None] = 'db51077434eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('priority', sa.String(), server_default=sa.text("'medium'"), nullable=False))
    op.add_column('signals', sa.Column('customer_identifier', sa.String(), nullable=True))
    op.create_index('idx_signals_customer_endpoint', 'signals', ['user_id', 'service_name', 'endpoint', 'customer_identifier', 'timestamp'], unique=False)
    op.create_index(op.f('ix_signals_customer_identifier'), 'signals', ['customer_identifier'], unique=False)
    op.create_index(op.f('ix_signals_priority'), 'signals', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_priority'), table_name='signals')
    op.drop_index(op.f('ix_signals_customer_identifier'), table_name='signals')
    op.drop_index('idx_signals_customer_endpoint', table_name='signals')
    op.drop_column('signals', 'customer_identifier')
    op.drop_column('signals', 'priority')
    # ### end Alembic commands ###
