"""rename stripe_customer_id to razorpay_customer_id

Revision ID: f1ff6bdd845c
Revises: c7261d00b88f
Create Date: 2026-03-02 13:06:43.326640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ff6bdd845c'
down_revision: Union[str, Sequence[str], None] = 'c7261d00b88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
