"""add billing fields to users table

Revision ID: ff4b0f4cac99
Revises: 6bb7f39ee70e
Create Date: 2026-03-02 12:23:31.174886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff4b0f4cac99'
down_revision: Union[str, Sequence[str], None] = '6bb7f39ee70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan_tier', sa.String(), server_default=sa.text("'free'"), nullable=True))
    op.add_column('users', sa.Column('signals_used_month', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('billing_period_start', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'billing_period_start')
    op.drop_column('users', 'signals_used_month')
    op.drop_column('users', 'plan_tier')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
