html_content = f"""
        <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
            <h2 style="color: #d32f2f;">🚨 Service Alert: {service_name}</h2>
            <div style="margin-bottom: 20px;">
                <p><strong>Endpoint:</strong> <code>{endpoint}</code></p>
                <p><strong>Reasoning:</strong></p>
                <div style="background-color: #ffebee; padding: 15px; border-radius: 4px; border-left: 4px solid #f44336;">
                    {ai_decision.get('reasoning')}
                </div>
            </div>
            
            <h3>Current Metrics</h3>
            <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
                <tr style="background-color: #f5f5f5;">
                    <th style="padding: 10px; text-align: left; border-bottom: 1px solid #ddd;">Metric</th>
                    <th style="padding: 10px; text-align: left; border-bottom: 1px solid #ddd;">Value</th>
                    <th style="padding: 10px; text-align: left; border-bottom: 1px solid #ddd;">Status</th>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">Average Latency</td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{avg_latency:.0f}ms</td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{'🔴 High' if avg_latency > 500 else '🟢 Normal'}</td>
                </tr>
                <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">Error Rate</td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{error_rate*100:.1f}%</td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">{'🔴 High' if error_rate > 0.15 else '🟢 Normal'}</td>
                </tr>
            </table>
            
            <p style="font-size: 12px; color: #666;">
                This alert was automatically generated by the AI Control Plane.
                Decision ID: {ai_decision.get('decision_id', 'N/A')}
            </p>
        </div>
        """